config/routes.rb
GiftList::Application.routes.draw do
  resources :lists

  match '/help', to: "static_pages#help"

  root :to => 'static_pages#home'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :list_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      flash[:success] = "We've added your request"
      redirect_to @list
    else
      flash[:error] = "We're sorry, but we couldn't save your list"
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      flash[:success] = "We've updated your list"
      redirect_to @list
    else
      flash[:error] = "We're sorry, but we couldn't update your list"
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id]).delete
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GiftList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <%= f.label :list_name, "Name" %>
  <%= f.text_field :list_name %>
  <br/>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List Details</h1>
<p>Use this page to makeu updates to your list</p>

<%= render 'form' %>

<%= link_to "Back to", '#' %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Create your List</h1>

<p>Let's setup a new list for your event.</p>

<%= render 'form' %>

<%#= link_to "Back to all Lists" lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.list_name %></h1>
<p>Here is the list of gifts that the invitee has setup.</p>

<p>If you have any questions you can contact us on <%= mail_to "bobandsarah@gmail.com"%></p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<html>
<head>
  <%= stylesheet_link_tag "application" %>
  <!-- <link type="text/css" rel="stylesheet" href="assets/stylesheets/application.css"> -->
  <title>Gift List</title>
</head>
<body>
  <header>
      <nav>
        <ul>
          <li>Register for gift list</li>
          <li>Manage your list</li>
          <li>Buy a gift</li>
          </ul>
        </nav>
    <p>GIFT LIST</p>

  </header>
  <article>
    <img id="mainpic" src="http://2.bp.blogspot.com/-E0oYG8kA9io/T3qzMvCuNZI/AAAAAAAAAKc/LjfpGRCHWBA/s1600/Wedding-Gift-Ideas-Unique1.jpg" alt="wedding present" />
    <h1>Welcome to Gift List!</h1>
    <h2>Gift list is a great service that allows users to:</h2>
    <ul>
      <li>Create and invite guests to an event you've set up</li>
      <li>Specify a 'gift list' related to the event</li>
      <li>See at a glance what gifts your guest list have committed to</li>
    </ul>
    <h3>More details coming soon!</h3>
    <h2>In the meantime please sign-up and we'll notify you when the service is up and running!!!!!</h2>
    </article>

    <div id="photo-container">
      <div class="photos">
        <a href="http://www.google.co.uk"><p>Register for gift list</p>
        <img src="http://pastor-dave.org/ESW/Images/register1.JPG" height="225" width="315"/></a>
      </div>

       <div class="photos">
        <p>Manage your list</p>
        <img src="http://interviewangel.com/blog/userfiles/weddings_bw2.jpg" height="225" width="315"/>
      </div>

      <div class="photos">
        <p>Buy a gift</p>
        <img src="http://4.bp.blogspot.com/-cd2I-F4ABM0/T9SmcdNi3EI/AAAAAAAAAFQ/1_NhQLfUYco/s1600/weddinggift%252C+wedding+gift%252C+wedding+gifts%252C+wedding+idea.gifts.jpg" height="225" width="315"/>
      </div>
    </div>

    <footer>
      <nav>
        <ul>
          <li><a href="mailto:richwisniewski@gmail.com?subject=Hello%20there">Contact</a></li>
          <li>About Us</li>
        </ul>
      </nav>
      <p>&copy Gift List
    </footer>
</body>
</html>